### ISSUE TITLE
Improved benchmarking with simulations

### ISSUE THREAD

**Issue by emdann** [MarioniLab/milo#19]
Following reviewer comments we need to compare performance of Milo and other methods in the following scenarios:

1. Complex topologies i.e. different from 1-D trajectory, including clusters
2. Batch effects: 
    1. of different magnitudes, 
    2. linear/non-linear
    3. simulation with 1 cluster from multiple batches
3. Non-uniform data densities (Not sure what this means exactly tho)
5. ..._did I miss something?_

**Data to use for benchmarking:** in the first version we simulate data and we simulate labels on top of that. I suggest we move to alternative simulation strategies:
1. Simulate conditions by using a similar but slightly different model for simulation: I found that in the [`dyngen` paper](https://www.biorxiv.org/content/10.1101/2020.02.06.936971v3.full.pdf) they implement a specific function [`generate_diff_abundance`](https://github.com/dynverse/dyngen_manuscript/blob/master/package/R/perturb_dataset.R) ([example usage](https://github.com/dynverse/dyngen_manuscript/blob/432d4969d9e177b75eb992aa6b51d6b4d32ee4cf/analysis/usecase_trajectory_alignment/3_explanation_plot.R#L40))
2. Use real data with synthetic labels: this would address (1) and (3) above ([scOpenProblems example](https://github.com/singlecellopenproblems/SingleCellOpenProblems/blob/299613ef0ee694fa84dd7770f01079c72dfe3bef/openproblems/tasks/differential_abundance/datasets/utils.py#L45)). We could also extend to address (4): take a dataset with batch effect, batch correct, assign labels, restart from dataset pre-correction, apply DA methods.

**Methods to benchmark**
- Louvain + GLM (personally I would ditch walktrap+GLM because I don't think it adds much, maybe we could just make a figure showing performance of different clustering strategies is similar just on one of the benchmarking scenarios) 
- Cydar
- DAseq
- MELD

**TODOs:**

- [x] Experimenting with adding batch effects of different magnitudes: taking inspiration from the [integration benchmark](https://github.com/theislab/scib) and other papers of integration methods, everyone uses [`splatter`](https://www.bioconductor.org/packages/release/bioc/vignettes/splatter/inst/doc/splat_params.html#22_Batch_parameters)
- [x] Make wrapper functions for the methods from [Mike's original implementation](https://github.com/MarioniLab/milo/blob/master/notebooks/2020-09-14_methods_comparison.Rmd) + MELD ([scOpenProblems example](https://github.com/singlecellopenproblems/SingleCellOpenProblems/blob/task/differential_abundance/openproblems/tasks/differential_abundance/methods/meld.py))
- [x] Implement simulated labels on real data
- [x] ...
